dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
name: docflow
description: A document and note template manager with Markdown support.
version: 1.3.5
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  gpt_markdown: ^1.1.4
  file_picker: ^8.0.3

flutter:
  generate: true
  uses-material-design: true
